name: CI Pipeline
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: echo "Installing npm packages"
      - run: npm install
      - run: echo "Running tests"
      - run: npm test
      - run: echo "Building the project"
      - run: npm build
